version: '3.9'

volumes:
  geoserver-data:


services:
    web:
      build:
        context: .
        dockerfile: ./Dockerfile
      ports:
        - 8000:8000
      restart: on-failure
      env_file:
        - ./.env
      healthcheck:
        test: curl --fail -s http://localhost:8000/geoserver/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3
    geoserver:
      image: kartoza/geoserver:2.21.1
      volumes:
        - geoserver-data:/opt/geoserver/data_dir2
      ports:
        - 8080:8080
      environment:
            - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir2
            - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/data_dir2/gwc2
            - GEOSERVER_ADMIN_PASSWORD=geoserver
            - GEOSERVER_ADMIN_USER=admin
            - INITIAL_MEMORY=2G
            - MAXIMUM_MEMORY=4G
      restart: on-failure
      healthcheck:
          test: curl --fail -s http://localhost:8080/ || exit 1
          interval: 1m30s
          timeout: 10s
          retries: 3
    gitlab:
      image: 'gitlab/gitlab-ee:latest'
      restart: always
      hostname: 'gitlab.hex360.com'
      environment:
        GITLAB_OMNIBUS_CONFIG: |
          external_url "http://gitlab.hex360.com:443"
          gitlab_rails['gitlab_shell_ssh_port'] = 22
          # Add any other gitlab.rb configuration here, each on its own line
      ports:
        - '81:80'
        - '443:443'
        - '22:22'
      volumes:
        - '$GITLAB_HOME/config:/etc/gitlab'
        - '$GITLAB_HOME/logs:/var/log/gitlab'
        - '$GITLAB_HOME/data:/var/opt/gitlab'
      shm_size: '256m'
