version: '3.9'

volumes:
  geo-db-data:


services:

  db:
    image: kartoza/postgis:14-3.1
    volumes:
      - geo-db-data:/var/lib/postgresql
    ports:
      - 5434:5434
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      - FORCE_SSL=TRUE
    restart: on-failure
    healthcheck:
      test: "exit 0"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
        DB_USER: docker
        DB_NAME: api
        DB_PASS: docker
        DB_HOST: db
        PORT: 5432
        DEBUG_TKT: True
    restart: on-failure
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s http://localhost:8000/geoserver/api/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
