version: '3.9'

volumes:
  geoserver-data:
  geo-db-data:


services:

  db:
    image: kartoza/postgis:14-3.1
    volumes:
      - geo-db-data:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=gis,gwc,geoserver
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      - FORCE_SSL=TRUE
    restart: on-failure
    healthcheck:
      test: "exit 0"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M

  geoserver:
    image: kartoza/geoserver:2.21.1
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/data_dir/gwc
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - GEOSERVER_ADMIN_USER=admin
      - INITIAL_MEMORY=2G
      - MAXIMUM_MEMORY=4G
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
