# Generated by Django 4.0.6 on 2022-09-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=200)),
                ('schema_name', models.CharField(max_length=200)),
                ('geoserver_title', models.CharField(default='null', max_length=200)),
                ('geoserver_style_uri', models.CharField(default='null', max_length=200)),
                ('geoserver_workspace', models.CharField(default='null', max_length=200)),
                ('geoserver_ip', models.CharField(default='null', max_length=200)),
            ],
            options={
                'verbose_name': 'metadado',
                'db_table': 'tb_metadata_geoserver',
            },
        ),
        migrations.CreateModel(
            name='Workspaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoserver_workspace', models.CharField(default='null', max_length=200)),
            ],
            options={
                'db_table': 'tb_geoserver_workspces',
            },
        ),
    ]
