# Generated by Django 4.0.6 on 2022-09-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pg_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('dbname', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=10)),
                ('authtk', models.CharField(blank=True, max_length=400)),
            ],
            options={
                'verbose_name': 'PostgreSql User',
            },
        ),
        migrations.CreateModel(
            name='UsersGeoserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoserver_ip', models.CharField(max_length=200)),
                ('geoserver_user', models.CharField(max_length=50)),
                ('geoserver_password', models.CharField(max_length=200)),
                ('authtk', models.CharField(blank=True, max_length=400)),
            ],
            options={
                'verbose_name': "Geoserve's User",
            },
        ),
    ]
